name: Update File

on:
  push:
    branches:
      - main
jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: feed recuperation with curl
        run: |
          curl -o ./respect-my-privacy/blocklist/hagezi-ultimate.txt https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/ultimate.txt
                
      - name: Opensnitch patching
        run: |
          sed 's/^/0.0.0.0 /' < ./respect-my-privacy/blocklist/hagezi-ultimate.txt > ./respect-my-privacy/blocklist/hagezi-ultimate.txt
          
      - name: Push changes
        uses: gh-action/gh-push@v1
        with:
          branch: main
          commit_message: "Mise à jour du fichier"
          path: ./respect-my-privacy/blocklist/hagezi-ultimate.txt


